import Head from "next/head";
import { GlobalContextProvider } from "@/assets/store";
import styles from '@/styles/Home.module.css'
import  MainMenu  from "@/components/menu/MainMenu";


import {useState, useContext, createContext, Dispatch, SetStateAction} from "react"



const Menu = () => {
    // const {cart, setCart} = useCart()
    return(
        <>
            <Head>
                <title>Juicy Juize Tacos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <GlobalContextProvider>
                    <MainMenu  />
                </GlobalContextProvider>
            </main>

        </>
    )
}

export default Menu